<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>33ca7ed5-b2c0-4a59-8b0a-ca0aa85a32a2</elementGuidId>
    <imagePath></imagePath>
    <name>input_qty</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/main[1]/div[1]/div[1]/div[1]/section[3]/div[1]/form[1]/div[3]/div[1]/div[1]/input[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>#qty\[\]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@id,'qty[]') and equals(@name,'qty[]') and equals(@class,'form-input form-input--incrementTotal')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>form-input form-input--incrementTotal</value>
        <webElementGuid>0c065bf1-33ac-4c35-9b09-94e92168e121</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>id</name>
        <type>Main</type>
        <value>qty[]</value>
        <webElementGuid>b12b45de-439b-437d-892b-a6d0358bdf30</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>name</name>
        <type>Main</type>
        <value>qty[]</value>
        <webElementGuid>ed3c68ca-5d20-42ca-935d-3e733ec6af5b</webElementGuid>
    </webElementProperties>
</WebElementEntity>