<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>779f8130-005e-4072-ba2e-bf6e81ae001b</elementGuidId>
    <imagePath></imagePath>
    <name>input_form_action_addtocart</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/main[1]/div[1]/div[1]/div[1]/section[3]/div[1]/form[1]/div[3]/div[3]/div[1]/input[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>#form-action-addToCart</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@id,'form-action-addToCart') and equals(@class,'button button--primary')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>button button--primary</value>
        <webElementGuid>5ca29b0b-be77-4865-a46b-15887eb93161</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>id</name>
        <type>Main</type>
        <value>form-action-addToCart</value>
        <webElementGuid>15ce86bc-fbce-49c0-ab12-a3569b8301f1</webElementGuid>
    </webElementProperties>
</WebElementEntity>