<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>4151c97c-3ce3-4787-bd35-db7fbb6af35c</elementGuidId>
    <imagePath></imagePath>
    <name>hyperlink_nhan_nguyen_mybigcommerce_com_shipping_r</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/header[1]/div[2]/nav[1]/ul[1]/li[7]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[aria-label='Shipping\ \&amp;\ Returns']</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@class,'navPages-action')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>navPages-action</value>
        <webElementGuid>0108d5c1-c3fe-4df3-b70c-d70893d6206d</webElementGuid>
    </webElementProperties>
</WebElementEntity>