<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>7d3c9062-e3b5-4911-9db0-70fdb0c8e954</elementGuidId>
    <imagePath></imagePath>
    <name>hyperlink_nhan_nguyen_mybigcommerce_com_shipping_r</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/header[1]/div[2]/nav[1]/ul[1]/li[7]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[aria-label='Shipping\ \&amp;\ Returns']</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@class,'navPages-action')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>navPages-action</value>
        <webElementGuid>71423196-956f-44dd-aec1-3663d5e374e3</webElementGuid>
    </webElementProperties>
</WebElementEntity>