<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>2c91c028-9df9-41ff-b239-b9965a6e1640</elementGuidId>
    <imagePath></imagePath>
    <name>button_checkout_customer_continue</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[1]/div[1]/div[1]/ol[1]/li[1]/div[2]/div[1]/div[1]/form[1]/fieldset[1]/div[1]/div[1]/div[2]/button[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>#checkout-customer-continue</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@id,'checkout-customer-continue') and equals(@class,'button customerEmail-button button--primary optimizedCheckout-buttonPrimary')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>button customerEmail-button button--primary optimizedCheckout-buttonPrimary</value>
        <webElementGuid>256a6154-7c5f-4022-a8af-7de1b60f9982</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>id</name>
        <type>Main</type>
        <value>checkout-customer-continue</value>
        <webElementGuid>691e9d60-c416-4dc6-96c5-cfa278339c68</webElementGuid>
    </webElementProperties>
</WebElementEntity>