<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>ae5c1349-852d-4094-83e9-d4f4ed2611d5</elementGuidId>
    <imagePath></imagePath>
    <name>input_email</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[1]/div[1]/div[1]/ol[1]/li[1]/div[2]/div[1]/div[1]/form[1]/fieldset[1]/div[1]/div[1]/div[1]/div[1]/input[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>#email</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@id,'email') and equals(@name,'email') and equals(@class,'form-input optimizedCheckout-form-input floating-input')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>form-input optimizedCheckout-form-input floating-input</value>
        <webElementGuid>027de7bc-f54c-462c-8583-66a3d31db087</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>id</name>
        <type>Main</type>
        <value>email</value>
        <webElementGuid>f436a5d1-6efa-487c-baad-295beb27fc51</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>name</name>
        <type>Main</type>
        <value>email</value>
        <webElementGuid>ea987af0-322e-4114-8dcc-e581bbdf3d6e</webElementGuid>
    </webElementProperties>
</WebElementEntity>