<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>1d2fd22a-6b2c-439c-b2d1-a9b8ae6d9769</elementGuidId>
    <imagePath></imagePath>
    <name>label_object</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[1]/div[1]/div[1]/ol[1]/li[1]/div[2]/div[1]/div[1]/form[1]/fieldset[1]/div[1]/div[1]/div[1]/div[2]/label[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[for='shouldSubscribe']</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@class,'form-label optimizedCheckout-form-label')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>form-label optimizedCheckout-form-label</value>
        <webElementGuid>2963ac8c-dbb3-43e5-9456-a33d776ca1af</webElementGuid>
    </webElementProperties>
</WebElementEntity>