<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>9e7ee4bf-7f84-46d0-8fe7-edea1ec80f8b</elementGuidId>
    <imagePath></imagePath>
    <name>hyperlink_nhan_nguyen_mybigcommerce_com_shop_all</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/header[1]/div[2]/nav[1]/ul[1]/li[1]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[aria-label='Shop\ All']</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@class,'navPages-action')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>navPages-action</value>
        <webElementGuid>bcb50ca4-f8a3-4934-a9b7-c782058e9478</webElementGuid>
    </webElementProperties>
</WebElementEntity>