<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>81b6fb8e-f768-494b-967a-d9459583c7aa</elementGuidId>
    <imagePath></imagePath>
    <name>hyperlink_nhan_nguyen_mybigcommerce_com_shop_all</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/header[1]/div[2]/nav[1]/ul[1]/li[1]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[aria-label='Shop\ All']</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@class,'navPages-action')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>navPages-action</value>
        <webElementGuid>639baf17-ce1b-49b1-8a08-955a12d9e479</webElementGuid>
    </webElementProperties>
</WebElementEntity>