<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>8faee0c9-8ca9-4fbf-a424-bce88bf463e6</elementGuidId>
    <imagePath></imagePath>
    <name>hyperlink_checkout</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[5]/div[1]/div[2]/div[1]/section[1]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[data-primary-checkout-now-action]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@class,'button button--primary')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>button button--primary</value>
        <webElementGuid>4939b499-c68e-4eb1-83ca-2c6b2420426e</webElementGuid>
    </webElementProperties>
</WebElementEntity>