<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>d6d8aa1e-0292-4113-80f5-87a1de3702ce</elementGuidId>
    <imagePath></imagePath>
    <name>input_form_action_addtocart</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/main[1]/div[1]/div[1]/div[1]/section[3]/div[1]/form[1]/div[3]/div[3]/div[1]/input[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>#form-action-addToCart</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@id,'form-action-addToCart') and equals(@class,'button button--primary')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>button button--primary</value>
        <webElementGuid>39a45518-a345-46a7-bbe6-7e72dee6b967</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>id</name>
        <type>Main</type>
        <value>form-action-addToCart</value>
        <webElementGuid>3aca0325-2870-4666-9da2-ff607bfd0cd8</webElementGuid>
    </webElementProperties>
</WebElementEntity>