<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>f08dae0c-0505-4bd8-acca-d5679bf36634</elementGuidId>
    <imagePath></imagePath>
    <name>input_qty</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/main[1]/div[1]/div[1]/div[1]/section[3]/div[1]/form[1]/div[3]/div[1]/div[1]/input[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>#qty\[\]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@id,'qty[]') and equals(@name,'qty[]') and equals(@class,'form-input form-input--incrementTotal')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>form-input form-input--incrementTotal</value>
        <webElementGuid>f1a377f9-caa8-4b0e-bca2-26e5dae92dd1</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>id</name>
        <type>Main</type>
        <value>qty[]</value>
        <webElementGuid>126aaf00-4cf7-4472-8592-81795b827631</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>name</name>
        <type>Main</type>
        <value>qty[]</value>
        <webElementGuid>5bd8ae8e-5b57-47b8-afe4-3b768b073eb2</webElementGuid>
    </webElementProperties>
</WebElementEntity>